apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: todo-app:latest # Ton image locale
          imagePullPolicy: Never # Important pour utiliser l'image locale
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: postgres-service # Nom du service PostgreSQL
            - name: POSTGRES_DB
              value: todo
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
